### ISSUE TITLE
Demo makefile aborts due to connector startup timeout

### ISSUE THREAD

**Issue by selfscrum** [confluentinc/data-mesh-demo#66]
when following the demo procedure for use with docker (make data-mesh), the script fails when waiting for the datagen_stocktrades connector to start up. It sticks in status "Provisioning" until finally the 600 sec timeout triggers. This is consistent with the information from the web console and the confluent CLI information delivered with "connect list" which both show that the connector is stuck in status "Provisioning" even after > 30 minutes. 

However after about 12-15 minutes, the data production starts anyways. So I was able to bypass the error by increasing the timeout to 1200 and removing the " || exit 1" part from the ccloud::wait_for_connector_up() script. So I have a workaround...

All datagen connectors are showing that behaviour.

**Comment by rspurgeon** [comment]
@selfscrum thank you for trying out the demo and filing the issue you had. We are aware there are various time delays and occassional failures in the connector provisioning.  We have fiddled with the timeouts and landed on the 600s, but I'm sorry to hear that wasn't sufficient for your case.

If you continue to have issues with connector provisioning, please contact the Confluent Cloud support with your environment and cluster IDs so they can try and track down the failures and improve the service.
