### ISSUE TITLE
Alternate option to try out the data mesh demo on local deployment  of Confluent

### ISSUE THREAD

**Issue by jairajak** [confluentinc/data-mesh-demo#70]
Appreciate if it is possible to post detailed steps to try out the data mesh demo on local deployment of confluent.

**Comment by rspurgeon** [comment]
@jairajak Thank you for evaluating the demo. The demo utilizes a Confluent Cloud only service called the [Streams Catalog](https://docs.confluent.io/cloud/current/stream-governance/stream-catalog.html) to store metadata about data products in the data mesh.  Right now I'm not aware of a timeline for making the streams catalog available as a Confluent Platform component, as such, we can't run the demo with local Confluent Platform at this time.
