### ISSUE TITLE
"aws" is not an available cloud provider

### ISSUE THREAD

**Issue by JBrejnholt** [confluentinc/data-mesh-demo#72]
Hi,

I'm trying to run the demo locally with a real Confluent cloud account. We are currently only running with Azure cloud provider. After cloning the repository and executed `make data-mesh`, an error ""aws" is not an available cloud provider" came up. Does this demo only work with aws? Do you have plans to cover Azure soon?

Many thanks!

**Comment by bellemare** [comment]
Hi @JBrejnholt, my sincere apologies for the delay. I hadn't had notifications on for new issues.

The `scripts/ccloud_library.sh` file contains references to `aws` CLI. However, while we do not use the aws CLI in this particular project, we do use this common ccloud_library.sh for a lot of helpful scripting on our end. 

You could either install aws-cli just to get around the installation checks, or you could edit the ccloud_library.sh file to remove references to aws. It doesn't seem like there are that many, but installing aws-cli would probably be easiest.
