### ISSUE TITLE
Error running the docker image

### ISSUE THREAD

**Issue by alexsalvo1** [confluentinc/data-mesh-demo#75]
At the end of the deploy I receive this error:

```
Congrats! The Data Mesh is ready to explore.

To destroy the Data Mesh environment including all resources in Confluent Cloud, run ->
    /Users/salessandro/Confluent/data-mesh-demo/scripts/destroy-data-mesh.sh stack-configs/java-service-account-sa-972pq7.config

Unable to find image 'cnfldemos/data-mesh-demo:0.0.52' locally
docker: Error response from daemon: manifest for cnfldemos/data-mesh-demo:0.0.52 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
make[1]: *** [run-docker] Error 125
make: *** [data-mesh] Error 2
```

Seems version 0.0.52 doesn't not exist. It should take latest or 0.0.51. I make the change to build.gradle file (line 12) putting version 0.0.51 and it works.

**Comment by bellemare** [comment]
Hi @alexsalvo1 

Sorry for the delay. I had no notifications of new issues and overlooked them all until now.

This particular issue was a release bug. It should have been 0.0.51.

However, I will be publishing an update to 0.0.52 with some new functionality (and error checking) shortly.
