### ISSUE TITLE
Unable to complete building process

### ISSUE THREAD

**Issue by mroiter-larus** [confluentinc/data-mesh-demo#81]
Hi,

i'm trying to setup the data-mesh-demo. 
I've run the `make data-mesh` and the environment is successfully created, as stated in the logs:

```
Confluent Cloud Environment:

Service Account         = sa-55d1gn
Confluent Cloud Cluster = lkc-prmr2o

Congrats! The Data Mesh is ready to explore.
```

In fact, i'm able to see and explore it from my Confluent Cloud `Environments` page.

The problem is that the local server does not complete the startup process. It remains hanging after the Docker image pull step:

```
To destroy the Data Mesh environment including all resources in Confluent Cloud, run ->
    /Users/mauroroiter/Documents/LARUS/workspaces/data-mesh-demo/scripts/destroy-data-mesh.sh stack-configs/java-service-account-sa-55d1gn.config

Unable to find image 'cnfldemos/data-mesh-demo:0.0.51' locally
0.0.51: Pulling from cnfldemos/data-mesh-demo
f3ef4ff62e0d: Pull complete 
706b9b9c1c44: Pull complete 
76205aac4d5a: Pull complete 
88a1d154ff66: Pull complete 
cf0c2b3f679d: Pull complete 
0c7e8a730fa2: Pull complete 
7809b2b7aeca: Pull complete 
d3ec3a949966: Pull complete 
Digest: sha256:fceeb157ccc8210cf9a8672585c432f4fb6662461c78f36056fef59e59b420e8
Status: Downloaded newer image for cnfldemos/data-mesh-demo:0.0.51
```

and if i try to go to `http://localhost:8080` i got a 404 error.

Note that i'm trying to run this demo into an Apple M1 chip. Given that, since the Docker image is built for `amd64` i had to run Colima in order to "virtualize" the correct architecture.

Could this be the issue?? Is there a way to run this demo on MacOs with Apple M1 chip?

Thanks in advance!

Mauro

**Comment by bellemare** [comment]
Hi Mauro, sorry for the delay. I didn't have notifications from this repo turned on. 

I can confirm that I am able to launch it off a clean install using `make data-mesh`, including pulling down the docker image on an M1. 

You may also want to try using `make data-mesh-from-source` to build it from source, and to avoid using docker at all. If you still have issues, please feel free to open a new ticket. I have notifications on now.
